AWSTemplateFormatVersion: '2010-09-09'
Description: Backenderer - GitHub OIDC deploy role (ECR + EC2 CFN + SSM)
Parameters:
  GitHubOwner:
    Type: String
    Description: Your GitHub username or org (allows any repo under it)
Resources:
  BackendererGitHubOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BackendererGitHubOIDC
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:${GitHubOwner}/*:*
      Policies:
        - PolicyName: BackendererDeployPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:CreateRepository
                  - ecr:DescribeRepositories
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteStack
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeImages
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstanceAttribute
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                  - ssm:ListCommandInvocations
                  - ssm:ListCommands
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource: "arn:aws:ssm:*:*:document/AWS-RunShellScript"
Outputs:
  DeployRoleArn:
    Description: Paste this into your fork as repo variable AWS_ROLE_ARN
    Value: !GetAtt BackendererGitHubOIDCRole.Arn
