name: Infra
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [dev, prod]
        default: dev
      action:
        type: choice
        options: [plan, apply, destroy]
        default: plan
      tf_version:
        type: string
        default: "1.6.6"

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=infra/terraform/envs/${{ inputs.env }} init -upgrade

      - name: Terraform ${{ inputs.action }}
        run: |
          cd infra/terraform/envs/${{ inputs.env }}
          case "${{ inputs.action }}" in
            plan) terraform plan ;;
            apply) terraform apply -auto-approve ;;
            destroy) terraform destroy -auto-approve ;;
          esac
